import { StyleSheet } from "react-native";
export const s = StyleSheet.create({
  buttons: {
    elevation: 8,
    backgroundColor: "#e0ac69",
    borderRadius: 10,
    height: 200,
    margin: 10,
    width: 150,
    flexDirection: "column",
  },
  buttonText: {
    fontFamily: "Roboto",
    fontSize: 14,
    flexWrap: "wrap",
    textAlign: "center",
    color: "#745151",
    flexDirection: "row",
  },
  thumbnailImage: {
    height: 150,
    width: 150,
    padding: 0,
    margin: 0,
    justifyContent: "flex-start",
    alignContent: "flex-start",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  centeredView: {
    flex: 1,
  },
  modalView: {
    margin: 41,
    backgroundColor: "white",
    borderRadius: 8,
    borderWidth: 2,
    padding: 0,
    alignItems: "center",
    shadowColor: "#000",
    position: "absolute",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    height: 625,
    width: 300,
    justifyContent: "center",
  },
  modalBackground: {
    backgroundColor: "#EDE8DC",
    flex: 1,
    paddingTop: 10,
    marginTop: 50,
    opacity: 0.9,
  },
  titles: {
    fontFamily: "serif",
    fontSize: 32,
    fontWeight: "black",
    textAlign: "justify",
    color: "#745151",
    marginLeft: 7,
  },
  headings: {
    marginVertical: 5,
    fontSize: 18,
    color: "#b69a82",
    fontFamily: "serif",
    marginLeft: 7,
  },
  details: {
    fontSize: 12,
    color: "grey",
    fontFamily: "serif",
    fontStyle: "italic",
    textAlign: "left",
    letterSpacing: 1,
    justifyContent: "center",
    marginLeft: 7,
    marginRight: 10,
  },
  images: {
    height: 200,
    width: 298,
    alignContent: "center",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginTop: 0,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 8,
  },
});
